### ISSUE TITLE
CGIのPOSTが 301 Moved Permanentlyになってしまって動かない

### ISSUE THREAD

**Issue by KaiMiyazawa** [deco-L/webserv#12]
`curl -v -X POST -d "username=user&password=pass" 127.0.0.1:8080/cgi/cgi_post.py`
を試してみてください。

本来、POSTのbodyに入れた"username=user&password=pass"を含めたhtmlが返ってくるcgi_post.pyが動くはずですが、
動かずに301が帰ってきています。

前回のmargeによる問題だと考えられます。

**Comment by deco-L** [comment]
動くようになりました。

**Comment by KaiMiyazawa** [comment]
僕の手元でも確認しました！すごい！
お疲れ様です！
