### ISSUE TITLE
/src/core/Socket.cppのINADDR_ANYは、結局追加したままでいいんでしたっけ？

### ISSUE THREAD

**Issue by KaiMiyazawa** [deco-L/webserv#18]
inet_addrが禁止関数なんでしたっけ？
ちょっと僕明確に理解してないんですが、調整の必要があればお願いします。
僕の理解と、レビューの時の回答のために、簡単に理由とかメモとかをディスカッションに残してくれてるとありがたいです。

**Comment by KaiMiyazawa** [comment]
79行目です。

**Comment by deco-L** [comment]
消します。後でやっておきます。
