### ISSUE TITLE
uri / cgi に入っている

### ISSUE THREAD

**Issue by deco-L** [deco-L/webserv#7]

**Comment by KaiMiyazawa** [comment]
`http://127.0.0.1:8080/`
の時に、CGIの処理が走ってる

**Comment by deco-L** [comment]
HttpGet.cpp
if ((!this->_cgi_extension.empty() && !this->_cgi_path.empty()) || this->_old_uri.size())
↓
if (!this->_cgi_extension.empty() && !this->_cgi_path.empty())
に変更しました。this->_old_uriがコンストラクタで必ず入っているので、この条件分岐だとGET methodは必ずcgiの処理に入ります。

HttpPost.cpp
if ((!this->_cgi_extension.empty() && !this->_cgi_path.empty()) || this->_cgi_relative_path.size())
↓
if (!this->_cgi_extension.empty() && !this->_cgi_path.empty())
に変更しました。this->_cgi_relative_pathはほとんど使っていないようだったので。

**Comment by KaiMiyazawa** [comment]
CGIのPOSTは #12 の問題でテストできませんが、
GETは挙動問題なさそうでした。
ありがとうございます。お疲れ様です！！
